name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag v0.3
        docker tag v0.3 387584877503.dkr.ecr.us-east-1.amazonaws.com/web-app:v0.3 && docker push 387584877503.dkr.ecr.us-east-1.amazonaws.com/web-app:v0.3
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile_mysql --tag v0.3
        docker tag v0.3 387584877503.dkr.ecr.us-east-1.amazonaws.com/my-sql:v0.3 && docker push 387584877503.dkr.ecr.us-east-1.amazonaws.com/my-sql:v0.3

